[aws]
profile = "*-dev"
region = "us-east-1"
account_id = "?"

[cur]
bucket_name = "*-dev-cur"
export_name = "cur-export"
prefix = "cur2"
time_granularity = "HOURLY"
include_resources = true
include_split_cost_allocation = true

[clickhouse]
host = "localhost"
port = 8123
user = "default"
password = ""
database = "aws_billing"
table = "cur_line_items"
secure = false

[state]
path = ".curhouse-state.json"
